import { describe, it, expect } from 'vitest';
import { generateBlocklist, buildRules } from '../src/engine/blocklist';
import type { BlocklistRule, AttackerIPSummary } from '../src/engine/types';

const NOW = new Date('2026-01-01T00:00:00.000Z');

function rule(ip: string, score: number): BlocklistRule {
  return { ip, format: 'plain', reason: 'x', score, enabled: true };
}
const three = [rule('5.5.5.5', 40), rule('8.8.8.8', 90), rule('9.9.9.9', 65)];

describe('generateBlocklist formats', () => {
  it('plain: one IP per line, sorted by score desc, with header', () => {
    const r = generateBlocklist(three, 'plain', { now: NOW });
    expect(r.text).toBe(
      '# Generated by LogGuard 2026-01-01T00:00:00.000Z\n# 3 IPs, min score 40\n8.8.8.8\n9.9.9.9\n5.5.5.5\n',
    );
    expect(r.count).toBe(3);
  });
  it('iptables', () => {
    const t = generateBlocklist(three, 'iptables', { now: NOW }).text;
    expect(t).toContain('iptables -A INPUT -s 8.8.8.8 -j DROP\n');
    expect(t).toContain('iptables -A INPUT -s 5.5.5.5 -j DROP\n');
  });
  it('iptables IPv6 uses ip6tables', () => {
    const t = generateBlocklist([rule('2001:db8::1', 50)], 'iptables', { now: NOW }).text;
    expect(t).toContain('ip6tables -A INPUT -s 2001:db8::1 -j DROP');
  });
  it('htaccess22: one header, one Deny line per IP', () => {
    const t = generateBlocklist(three, 'htaccess22', { now: NOW }).text;
    expect(t).toContain('Order Allow,Deny\nAllow from all\nDeny from 8.8.8.8\nDeny from 9.9.9.9\nDeny from 5.5.5.5\n');
    expect(t.match(/Order Allow,Deny/g)?.length).toBe(1);
  });
  it('htaccess24', () => {
    const t = generateBlocklist(three, 'htaccess24', { now: NOW }).text;
    expect(t).toContain(
      '<RequireAll>\n  Require all granted\n  Require not ip 8.8.8.8\n  Require not ip 9.9.9.9\n  Require not ip 5.5.5.5\n</RequireAll>\n',
    );
  });
  it('nginx', () => {
    const t = generateBlocklist(three, 'nginx', { now: NOW }).text;
    expect(t).toContain('deny 8.8.8.8;\ndeny 9.9.9.9;\ndeny 5.5.5.5;\n');
  });
  it('every format starts with the two comment lines', () => {
    for (const f of ['plain', 'iptables', 'htaccess22', 'htaccess24', 'nginx'] as const) {
      const lines = generateBlocklist(three, f, { now: NOW }).text.split('\n');
      expect(lines[0]).toMatch(/^# Generated by LogGuard \d{4}-/);
      expect(lines[1]).toBe('# 3 IPs, min score 40');
    }
  });
});

describe('generateBlocklist safety', () => {
  it('shell injection attempt is rejected', () => {
    const r = generateBlocklist([rule('1.2.3.4; rm -rf /', 99), rule('8.8.8.8', 50)], 'iptables', { now: NOW });
    expect(r.text).not.toContain('rm -rf');
    expect(r.count).toBe(1);
    expect(r.skipped[0].reason).toBe('invalid IP address');
  });
  it.each(['1.2.3.4\n5.6.7.8', '1.2.3.4 ', '$(whoami)', '`id`', '1.2.3.4|cat', '1.2.3.4;'])('rejects %j', (bad) => {
    const r = generateBlocklist([rule(bad, 90)], 'nginx', { now: NOW });
    expect(r.count).toBe(0);
    expect(r.skipped.length).toBe(1);
  });
  it('empty list gives header + no IPs qualified', () => {
    const r = generateBlocklist([], 'plain', { now: NOW });
    expect(r.text).toBe('# Generated by LogGuard 2026-01-01T00:00:00.000Z\n# 0 IPs, min score 0\n# no IPs qualified\n');
    expect(r.count).toBe(0);
  });
  it.each([
    ['10.1.2.3', 'private'],
    ['172.16.5.5', 'private'],
    ['172.31.255.255', 'private'],
    ['192.168.1.1', 'private'],
    ['127.0.0.1', 'loopback'],
    ['169.254.1.1', 'link-local'],
    ['100.64.0.1', 'CGNAT'],
    ['100.127.255.255', 'CGNAT'],
    ['::1', 'loopback'],
    ['fc00::1', 'unique-local'],
    ['fd12:3456::1', 'unique-local'],
    ['fe80::1', 'link-local'],
  ])('private/reserved %s skipped with reason', (ip, word) => {
    const r = generateBlocklist([rule(ip, 90)], 'plain', { now: NOW });
    expect(r.count).toBe(0);
    expect(r.skipped[0].ip).toBe(ip);
    expect(r.skipped[0].reason).toContain(word);
  });
  it('public IPs near private ranges are kept', () => {
    const r = generateBlocklist([rule('172.32.0.1', 50), rule('100.128.0.1', 50), rule('11.0.0.1', 50)], 'plain', { now: NOW });
    expect(r.count).toBe(3);
  });
  it('allowlisted IPs are skipped with a reason', () => {
    const r = generateBlocklist(three, 'plain', { now: NOW, allow: new Set(['8.8.8.8']) });
    expect(r.count).toBe(2);
    expect(r.skipped).toEqual([{ ip: '8.8.8.8', reason: 'allowlisted' }]);
  });
  it('duplicates are dropped, highest score kept', () => {
    const r = generateBlocklist([rule('8.8.8.8', 40), rule('8.8.8.8', 70)], 'plain', { now: NOW });
    expect(r.count).toBe(1);
    expect(r.text).toContain('# 1 IPs, min score 70');
  });
  it('disabled rules are ignored', () => {
    const r = generateBlocklist([{ ...rule('8.8.8.8', 90), enabled: false }], 'plain', { now: NOW });
    expect(r.count).toBe(0);
  });
});

describe('buildRules', () => {
  const base = { totalHits: 10, threatHits: 5, byType: { BRUTE_FORCE: 0, SQLI: 1, TRAVERSAL: 0, SCANNER_UA: 0, SENSITIVE_PROBE: 0 }, mainThreat: 'SQLI', firstSeen: 0, lastSeen: 1 } as const;
  const sums: AttackerIPSummary[] = [
    { ...base, ip: '1.1.1.1', score: 50, rating: 'MEDIUM' },
    { ...base, ip: '2.2.2.2', score: 85, rating: 'CRITICAL' },
    { ...base, ip: '3.3.3.3', score: 20, rating: 'LOW' },
  ];
  it('filters by min score, sorts desc, honours allowlist', () => {
    const r = buildRules(sums, 40, new Set(['1.1.1.1']));
    expect(r.map((x) => x.ip)).toEqual(['2.2.2.2']);
    expect(r[0].enabled).toBe(true);
  });
  it('keeps all above threshold', () => {
    expect(buildRules(sums, 40, new Set()).map((x) => x.ip)).toEqual(['2.2.2.2', '1.1.1.1']);
  });
});
