import type { AttackerIPSummary, BlocklistRule } from './types';
import { isValidIp } from './ip';

export type BlocklistFormat = BlocklistRule['format'];
export interface SkippedIp { ip: string; reason: string }
export interface BlocklistOptions { now?: Date; minScore?: number; allow?: Set<string> }

// Returns a reason string if the IP must never be blocked, otherwise null.
function reservedReason(ip: string): string | null {
  const lower = ip.toLowerCase();
  let v4 = lower;
  const mapped = /^::ffff:(\d{1,3}(?:\.\d{1,3}){3})$/.exec(lower);
  if (mapped) v4 = mapped[1];

  if (!v4.includes(':')) {
    const [a, b] = v4.split('.').map(Number);
    if (a === 10) return 'private range 10.0.0.0/8';
    if (a === 172 && b >= 16 && b <= 31) return 'private range 172.16.0.0/12';
    if (a === 192 && b === 168) return 'private range 192.168.0.0/16';
    if (a === 127) return 'loopback 127.0.0.0/8';
    if (a === 169 && b === 254) return 'link-local 169.254.0.0/16';
    if (a === 100 && b >= 64 && b <= 127) return 'CGNAT 100.64.0.0/10';
    return null;
  }
  if (lower === '::1' || lower === '0:0:0:0:0:0:0:1') return 'loopback ::1';
  if (/^f[cd][0-9a-f]{2}:/.test(lower)) return 'unique-local fc00::/7';
  if (/^fe[89ab][0-9a-f]:/.test(lower)) return 'link-local fe80::/10';
  return null;
}

function directive(ip: string, format: BlocklistFormat): string {
  switch (format) {
    case 'iptables':
      return `${ip.includes(':') ? 'ip6tables' : 'iptables'} -A INPUT -s ${ip} -j DROP`;
    case 'nginx':
      return `deny ${ip};`;
    default:
      return ip;
  }
}

export function generateBlocklist(
  rules: BlocklistRule[],
  format: BlocklistFormat,
  opts: BlocklistOptions = {},
): { text: string; count: number; skipped: SkippedIp[] } {
  const skipped: SkippedIp[] = [];
  const best = new Map<string, number>(); // ip -> highest score (also removes duplicates)

  for (const r of rules) {
    if (r.enabled === false) continue;
    const ip = typeof r.ip === 'string' ? r.ip.trim() : '';
    // SAFETY: the IP comes from an attacker-controlled log and may be pasted into a root shell.
    if (!isValidIp(ip) || r.ip !== ip) {
      skipped.push({ ip: String(r.ip).slice(0, 60), reason: 'invalid IP address' });
      continue;
    }
    if (opts.allow?.has(ip)) {
      skipped.push({ ip, reason: 'allowlisted' });
      continue;
    }
    const reserved = reservedReason(ip);
    if (reserved) {
      skipped.push({ ip, reason: reserved });
      continue;
    }
    const prev = best.get(ip);
    if (prev === undefined || r.score > prev) best.set(ip, r.score);
  }

  const ips = [...best.entries()].sort((a, b) => b[1] - a[1]).map(([ip]) => ip);
  const minScore = opts.minScore ?? (best.size ? Math.min(...best.values()) : 0);
  const iso = (opts.now ?? new Date()).toISOString();

  const lines: string[] = [`# Generated by LogGuard ${iso}`, `# ${ips.length} IPs, min score ${minScore}`];

  if (ips.length === 0) {
    lines.push('# no IPs qualified');
  } else if (format === 'htaccess22') {
    lines.push('Order Allow,Deny', 'Allow from all');
    for (const ip of ips) lines.push(`Deny from ${ip}`);
  } else if (format === 'htaccess24') {
    lines.push('<RequireAll>', '  Require all granted');
    for (const ip of ips) lines.push(`  Require not ip ${ip}`);
    lines.push('</RequireAll>');
  } else {
    for (const ip of ips) lines.push(directive(ip, format));
  }

  return { text: lines.join('\n') + '\n', count: ips.length, skipped };
}

// Pick the IPs worth blocking: score >= minScore and not allowlisted.
export function buildRules(summaries: AttackerIPSummary[], minScore: number, allow: Set<string>): BlocklistRule[] {
  return summaries
    .filter((s) => s.score >= minScore && !allow.has(s.ip))
    .sort((a, b) => b.score - a.score)
    .map((s) => ({
      ip: s.ip,
      format: 'plain' as const,
      reason: `${s.mainThreat}, score ${s.score}, ${s.threatHits} threat hits`,
      score: s.score,
      enabled: true,
    }));
}
