import type { BlocklistRule } from '../contracts';

export type BlocklistFormat = BlocklistRule['format'];

export function generateBlocklist(
  rules: BlocklistRule[],
  format: BlocklistFormat,
  minScore = rules.length > 0 ? Math.min(...rules.map((rule) => rule.score)) : 0,
): string {
  const header = [
    `# Generated by LogGuard on ${new Date().toISOString()} - review before applying`,
    `# ${rules.length} IPs, min score ${minScore}`,
  ];
  const ips = rules.map((rule) => rule.ip);

  let body: string[];
  switch (format) {
    case 'htaccess24':
      body = [
        '<RequireAll>',
        '  Require all granted',
        ...ips.map((ip) => `  Require not ip ${ip}`),
        '</RequireAll>',
      ];
      break;
    case 'htaccess22':
      body = ['Order Allow,Deny', 'Allow from all', ...ips.map((ip) => `Deny from ${ip}`)];
      break;
    case 'iptables':
      body = ips.map((ip) => `${ip.includes(':') ? 'ip6tables' : 'iptables'} -A INPUT -s ${ip} -j DROP`);
      break;
    case 'nginx':
      body = ips.map((ip) => `deny ${ip};`);
      break;
    case 'plain':
      body = ips;
      break;
  }

  return [...header, ...body].join('\n');
}
